# Generated by Django 5.1.5 on 2025-06-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotheque.media')),
                ('artiste', models.CharField(max_length=255)),
                ('nombre_pistes', models.PositiveIntegerField()),
            ],
            bases=('bibliotheque.media',),
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotheque.media')),
                ('realisateur', models.CharField(max_length=255)),
                ('duree', models.PositiveIntegerField(help_text='Durée en minutes')),
            ],
            bases=('bibliotheque.media',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotheque.media')),
                ('auteur', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
            ],
            bases=('bibliotheque.media',),
        ),
    ]
