# Generated by Django 5.1.5 on 2025-07-15 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_cd_dvd_livre'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotheque.media')),
                ('nombre_joueurs', models.PositiveIntegerField()),
                ('duree_estimee', models.DurationField()),
            ],
            bases=('bibliotheque.media',),
        ),
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
    ]
