# Generated by Django 5.1.5 on 2025-02-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='rendu',
            field=models.BooleanField(default=False),
        ),
    ]
