# Generated by Django 5.1.5 on 2025-07-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_jeudeplateau_remove_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='artiste',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cd',
            name='nombre_pistes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
