# Generated by Django 5.1.5 on 2025-07-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0004_alter_cd_artiste_alter_cd_nombre_pistes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='duree',
            field=models.PositiveIntegerField(blank=True, help_text='Durée en minutes', null=True),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='realisateur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='duree_estimee',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='nombre_joueurs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
